file_format: "1"
id: Zippy
name: Zippy
type: shield
url: https://github.com/MakotoKurauchi/Zippy
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - Zippy_left
  - Zippy_right
